# Generated by Django 3.2.18 on 2023-04-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('client_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Pending Approval'), (2, 'Published')], default=0)),
                ('finished', models.BooleanField(default=False)),
                ('tagline', models.CharField(max_length=20)),
            ],
        ),
    ]
