# Generated by Django 3.2.18 on 2023-04-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_on']},
        ),
    ]
