# Generated by Django 3.2.18 on 2023-04-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='tagline',
            field=models.CharField(max_length=50),
        ),
    ]
