# Generated by Django 3.2.18 on 2023-05-10 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alt_image',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
